sudo: required
dist: trusty
language: node_js
node_js:
- 6.9.5
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install
- ng build
script: karma start karma.conf.js --single-run
deploy:
- provider: s3
  access_key_id: AKIAID3OLT4CEU2LVPJQ
  secret_access_key: &1
    secure: nAyi2B8YeEbjj+1DmGor5+Ag9FnQVDwtLsm4qkcCt3ljf50MlSkwTfASVeygKvrw/B2nsXG8lXncby5ZgSqzg0eH09wm3YlvrmcbfTjR8B81xTEa5LxjWs1SINoMwfueDmYB89VyYf1pNRogrNClzeo3TuLII8gfG/kiSPOfCDo5+VR/wRDiKLN8mvRuPltNjXjBnh5S5Gye0j0Spz91CtZbqxJbmJDzi4IbEOMUeooILp0puZlrG+p9ulYv5umqnSAFPDFmr6iOkx7Qa8pejqqvOC0ME7pIW1CqVyU7dE0us01W3MhT7f0NNvkvI5RdW8HEP9vYz8eYbWy16aoBAgf9k+TVEmMCRdWWGLEobDgA5g3BzRtxXTLehBZ6XIy5GNP0qqu7xdhgSDT6ygJjDEH8/ye4zCS0ksG/6pJqfqonc6SnhQnRak5Os3xsZP3r74OqlULRKGkVc7PcMaNG8x5DcWslvGQZp5cOAAqh7PyQSrf5hTEbjEMkTytLvHaFE92fAqbsVDgbTP9CH0TpWVV9hfuXjWtNTdo+LpvTK4lkrA6ZjcWwoN67pfdRHZpBwv0e31duLDpu585vZw9iphK8HT2uyw0ADFF/iONC31JQASq/N2Tjo8/npeTnMK1/FpP+y6zR9ZRoA381UYNLAJeI+z8rgnSLxJxY9KXV+BY=
  local_dir: dist
  skip_cleanup: true
  on: &2
    repo: amitrke/courtres-ng
  bucket: aws-website-amitkumar-iobhb
- provider: codedeploy
  access_key_id: AKIAID3OLT4CEU2LVPJQ
  secret_access_key: *1
  bucket: aws-website-amitkumar-iobhb
  application: courtres-ng
  deployment_group: ''
  on: *2