# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:14-browsers
        env:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: yarn build
      # run tests!
      - run: yarn test
      
      - store_artifacts:
          path: coverage
          
      - run: 
          name: codecov report upload
          command: ~/repo/node_modules/.bin/codecov -f ~/repo/coverage/* -t 02afbfa5-18d9-44a8-b617-62db006e222b

      # - run:
      #     name: Install dependencies
      #     working_directory: /
      #     command: |
      #       sudo apt-get -y -qq install awscli

      # - deploy:
      #     name: Deploy to S3 if tests pass and branch is Master
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         aws s3 sync dist s3://aws-website-amitkumar-iobhb/ --delete
      #       else
      #         echo "Not master branch so not deploying"
      #       fi
