# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - run:
          name: Install Chrome Dependencies
          command: sudo apt-get install lsb-release libxss1 libappindicator1 libindicator7 libgconf2-4 libnss3-1d libasound2 libgtk-3-0 libxtst6 fonts-liberation xdg-utils
      - run:
          name: Download Chrome
          command: |
            mkdir -p chrome-archive
            wget -qnc https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O chrome-archive/google-chrome-stable_current_amd64.deb
      - run:
          name: Install Chrome
          command: |
            sudo dpkg -i chrome-archive/google-chrome*.deb # Might show "errors", fixed by next line
            sudo apt-get install -f
      - run:
          name: Print Chrome Version
          command: google-chrome --version

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
